name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Checkout and Test code
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test code
      run: go test ./...

    - name: build code
      run: go build -o curtaincall ./cmd/web

    - uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CURTAINCALL_HOSTNAME }}
        username: ${{ secrets.CURTAINCALL_SSH_USER }}
        key: ${{ secrets.CURTAINCALL_SSH_KEY }}
        source: curtaincall,web/*
        target: /home/${{ secrets.JAMQL_SSH_USER }}/
