name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Checkout and Test code
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Checkout code
      uses: actions/checkout@v2

    - name: package frontend, backends, and scripts
      run: make dist

    - name: deploy frontend files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CC_HOSTNAME }}
        username: ${{ secrets.CC_SSH_USER }}
        key: ${{ secrets.CC_SSH_KEY }}
        source: dist/*
        strip_components: 1
        target: /home/${{ secrets.CC_SSH_USER }}/

    - name: remove db
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CC_HOSTNAME }}
        username: ${{ secrets.CC_SSH_USER }}
        key: ${{ secrets.CC_SSH_KEY }}
        script: rm curtaincall.db

    - name: initalize DB
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CC_HOSTNAME }}
        username: ${{ secrets.CC_SSH_USER }}
        key: ${{ secrets.CC_SSH_KEY }}
        script: sqlite3 curtaincall.db < setup.sql

    - name: restart application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CC_HOSTNAME }}
        username: ${{ secrets.CC_SSH_USER }}
        key: ${{ secrets.CC_SSH_KEY }}
        script: sudo systemctl restart curtaincall
